/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccsPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Alyph
 */
public class FrameRelatorio extends javax.swing.JDialog {


    /**
     * Creates new form FrameRelatorio
     */
   
     
    public FrameRelatorio() {
        initComponents();
        this.setModal(true);
        
        this.setIconImage(new ImageIcon("C:\\Users\\Alyph\\OneDrive\\Documentos\\NetBeansProjects\\CentralControlSystem\\src\\ccsImagens\\Icons\\iconRelatorio.png").getImage());
    
    }
  static Connection con;  
  static  boolean conectado;
public  static void ConectionStringMysql()
{  
 try {          
            // cria uma variavel de conexão
            // cria "pega" uma conexão com o banco
            con = DriverManager.getConnection("jdbc:mysql://localhost/teste", "root", "admin"); 
      conectado = true;
     //  System.out.println("SUCESSO!");
        } catch (SQLException e){
           // System.out.println("Ocorreu um erro de SQL" + e.getMessage());
        } 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("teste?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        produtosQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produtos p");
        produtosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery.getResultList();
        produtosQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produtos p");
        produtosList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery1.getResultList();
        comprasQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Compras c");
        comprasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : comprasQuery.getResultList();
        produtosQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produtos p");
        produtosList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery2.getResultList();
        produtosQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produtos p");
        produtosList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery3.getResultList();
        produtosQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produtos p");
        produtosList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery4.getResultList();
        produtosQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produtos p");
        produtosList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery5.getResultList();
        labelRelatorio = new javax.swing.JLabel();
        ButtonFechar = new javax.swing.JButton();
        jScrollPaneCompras = new javax.swing.JScrollPane();
        tblRelatorio = new javax.swing.JTable();
        txtDataIni = new javax.swing.JFormattedTextField();
        txtDataIni1 = new javax.swing.JFormattedTextField();
        jLabel_DataIni = new javax.swing.JLabel();
        jLabel_DataFim = new javax.swing.JLabel();
        jButtonGerarRel = new javax.swing.JButton();
        jLabel_relItens = new javax.swing.JLabel();
        txtRELIR = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtReLucroLiquido = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRelQTD = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRelQTD1 = new javax.swing.JFormattedTextField();
        jComboBox_descricao = new javax.swing.JComboBox<>();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Central Control System - Relatório");

        labelRelatorio.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        labelRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRelatorio.setText("Relatório");

        ButtonFechar.setText("Fechar");
        ButtonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonFecharMouseClicked(evt);
            }
        });
        ButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFecharActionPerformed(evt);
            }
        });

        tblRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Valor", "Qtd", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneCompras.setViewportView(tblRelatorio);

        try {
            txtDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataIniActionPerformed(evt);
            }
        });

        try {
            txtDataIni1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataIni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataIni1ActionPerformed(evt);
            }
        });

        jLabel_DataIni.setText("Data Inicial");

        jLabel_DataFim.setText("Data Final");

        jButtonGerarRel.setText("Gerar Relatório");
        jButtonGerarRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelActionPerformed(evt);
            }
        });

        jLabel_relItens.setText("Entrada / Saída de Itens Vendidos");

        txtRELIR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRELIR.setEnabled(false);

        jLabel12.setText("Total de IR");

        txtReLucroLiquido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtReLucroLiquido.setEnabled(false);

        jLabel13.setText("Total de Itens");

        txtRelQTD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRelQTD.setEnabled(false);
        txtRelQTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelQTDActionPerformed(evt);
            }
        });

        jLabel14.setText("Total de Itens Vendidos");

        jLabel15.setText("Total de Itens Comprados");

        txtRelQTD1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRelQTD1.setEnabled(false);
        txtRelQTD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelQTD1ActionPerformed(evt);
            }
        });

        jComboBox_descricao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_relItens)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReLucroLiquido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(43, 43, 43)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRELIR, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRelQTD)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRelQTD1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ButtonFechar)
                        .addComponent(jScrollPaneCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_DataIni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DataFim)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataIni1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGerarRel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DataIni)
                    .addComponent(jLabel_DataFim))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGerarRel)
                    .addComponent(jComboBox_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataIni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_relItens)
                            .addGap(7, 7, 7)
                            .addComponent(jScrollPaneCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(7, 7, 7)
                                    .addComponent(txtReLucroLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(7, 7, 7)
                                    .addComponent(txtRelQTD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(7, 7, 7)
                            .addComponent(txtRelQTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addComponent(txtRELIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonFechar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonFecharMouseClicked

        int opcao = JOptionPane.showConfirmDialog(null,"Realmente deseja sair?","Central Control System - Compra", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
        }
        else if (opcao == JOptionPane.NO_OPTION){
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_ButtonFecharMouseClicked

    private void ButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonFecharActionPerformed

    private void txtDataIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataIniActionPerformed

    private void txtDataIni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataIni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataIni1ActionPerformed
public  void SelectTables() throws SQLException
{
    if(conectado == false){ConectionStringMysql();}
    String Query_COMPRAS = "select * from teste.compras;";
    String Query_VENDAS = "select * from teste.vendas;"; 
    String Query = null;
    String Tipo = null,Descricao,Valor,Qnt,DT = "";
    
/// Strings depara Vendas e Compras (database)
    String Cab_val = null;
    String Cab_Qnt = null;
    String Cab_Dat = null;
      
        double i_c = 0;
        double qnt_vendas = 0;
        double qnt_compras = 0;
       
    for(int i =0;i<2;i++){
        switch(i)
        {
            case 0:
                
                    Query = Query_COMPRAS;
                    Tipo = "Compras";
                    Cab_val = "valor";
                    Cab_Qnt = "quantidade";
                    Cab_Dat = "data";
                    break;
            case 1:
               
                Query = Query_VENDAS; 
                Tipo = "Vendas";
                Cab_val = "valor_venda";
                Cab_Qnt = "quantidade_venda";
                Cab_Dat = "data_venda";            
            break;
        }
       PreparedStatement c_compras = con.prepareStatement(Query);
        ResultSet rs_c = c_compras.executeQuery();
        while (rs_c.next())
        {
           Descricao = rs_c.getString("Descricao");
           Valor = rs_c.getString(Cab_val);
           Qnt = rs_c.getString(Cab_Qnt);
           AddRow(Tipo,Descricao,Valor,Qnt,DT);          
           i_c++;
           if(Tipo == "Compras")
           {
               qnt_compras++;   
           }
           if(Tipo == "Vendas")
            {
                qnt_vendas++;
           }
        }
    
        Query = null;
        rs_c.close();
}
    txtReLucroLiquido.setValue(i_c);
    txtRelQTD.setValue(qnt_vendas);
    txtRelQTD1.setValue(qnt_compras);
}

public  void AddRow(String Tipo, String Descricao, String Valor, String Qnt, String DT){
  DefaultTableModel model = (DefaultTableModel) tblRelatorio.getModel();
  model.addRow(new Object[]{Tipo, Descricao, Valor,Qnt,DT});
}
    private void jButtonGerarRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelActionPerformed

        try {
            if(conectado == false){ConectionStringMysql();}
            SelectTables();
        } catch (SQLException ex) {
            Logger.getLogger(FrameRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
           
     
       
    }//GEN-LAST:event_jButtonGerarRelActionPerformed

    private void txtRelQTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelQTDActionPerformed
   
    }//GEN-LAST:event_txtRelQTDActionPerformed

    private void txtRelQTD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelQTD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRelQTD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRelatorio().setVisible(true);
             
                        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonFechar;
    private java.util.List<ccsPackage.Compras> comprasList;
    private javax.persistence.Query comprasQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButtonGerarRel;
    private javax.swing.JComboBox<String> jComboBox_descricao;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel_DataFim;
    private javax.swing.JLabel jLabel_DataIni;
    private javax.swing.JLabel jLabel_relItens;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPaneCompras;
    private javax.swing.JLabel labelRelatorio;
    private java.util.List<ccsPackage.Produtos> produtosList;
    private java.util.List<ccsPackage.Produtos> produtosList1;
    private java.util.List<ccsPackage.Produtos> produtosList2;
    private java.util.List<ccsPackage.Produtos> produtosList3;
    private java.util.List<ccsPackage.Produtos> produtosList4;
    private java.util.List<ccsPackage.Produtos> produtosList5;
    private javax.persistence.Query produtosQuery;
    private javax.persistence.Query produtosQuery1;
    private javax.persistence.Query produtosQuery2;
    private javax.persistence.Query produtosQuery3;
    private javax.persistence.Query produtosQuery4;
    private javax.persistence.Query produtosQuery5;
    private javax.swing.JTable tblRelatorio;
    private javax.swing.JFormattedTextField txtDataIni;
    private javax.swing.JFormattedTextField txtDataIni1;
    private javax.swing.JFormattedTextField txtRELIR;
    private javax.swing.JFormattedTextField txtReLucroLiquido;
    private javax.swing.JFormattedTextField txtRelQTD;
    private javax.swing.JFormattedTextField txtRelQTD1;
    // End of variables declaration//GEN-END:variables

    private String String(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
