/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccsPackage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alyph
 */
public class FrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
        this.setIconImage(new ImageIcon("C:\\CentralControlSystem\\src\\ccsImagens\\Icons\\iconCCS.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonCompra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtomRelatorio = new javax.swing.JButton();
        ButtomVenda = new javax.swing.JButton();
        ButtonCadastro = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuItemCompra = new javax.swing.JMenuItem();
        menuItemVenda = new javax.swing.JMenuItem();
        menuItemRelatorio = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        sobreItemCreditos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Central Control System");
        setLocation(new java.awt.Point(500, 350));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1060, 538));
        setResizable(false);
        setSize(new java.awt.Dimension(1060, 538));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Central Control System - CCS");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ccsImagens/imgRelatorio.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(321, 286));
        jLabel1.setMinimumSize(new java.awt.Dimension(321, 286));
        jLabel1.setName("ImgCompra"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(321, 286));

        ButtonCompra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ButtonCompra.setText("Compra");
        ButtonCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCompraMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ccsImagens/imgCompra.png"))); // NOI18N
        jLabel3.setName("ImgCompra"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ccsImagens/imgVenda.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setName("ImgCompra"); // NOI18N

        ButtomRelatorio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ButtomRelatorio.setText("Relatório");
        ButtomRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtomRelatorioMouseClicked(evt);
            }
        });

        ButtomVenda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ButtomVenda.setText("Venda");
        ButtomVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtomVendaMouseClicked(evt);
            }
        });

        ButtonCadastro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ButtonCadastro.setText("Cadastro");
        ButtonCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCadastroMouseClicked(evt);
            }
        });
        ButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastroActionPerformed(evt);
            }
        });

        menuBar.setBorder(null);
        menuBar.setForeground(new java.awt.Color(240, 240, 240));
        menuBar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        menuMenu.setText("Menu");
        menuMenu.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem2.setText("Cadastro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuMenu.add(jMenuItem2);

        menuItemCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemCompra.setText("Compra");
        menuItemCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemCompraMouseClicked(evt);
            }
        });
        menuItemCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCompraActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemCompra);

        menuItemVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuItemVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemVenda.setText("Venda");
        menuItemVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemVendaMouseClicked(evt);
            }
        });
        menuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendaActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemVenda);

        menuItemRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemRelatorio.setText("Relatório");
        menuItemRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemRelatorioMouseClicked(evt);
            }
        });
        menuItemRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemRelatorio);

        menuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemSair.setText("Sair");
        menuItemSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemSairMouseClicked(evt);
            }
        });
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemSair);

        menuBar.add(menuMenu);

        menuSobre.setText("Sobre");
        menuSobre.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        sobreItemCreditos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        sobreItemCreditos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sobreItemCreditos.setText("Créditos");
        sobreItemCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreItemCreditosMouseClicked(evt);
            }
        });
        sobreItemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreItemCreditosActionPerformed(evt);
            }
        });
        menuSobre.add(sobreItemCreditos);

        menuBar.add(menuSobre);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtomVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtomRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtomVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtomRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel2.getAccessibleContext().setAccessibleName("labelMenuNome");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendaActionPerformed

        frameVenda();
        
    }//GEN-LAST:event_menuItemVendaActionPerformed

    private void ButtonCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCompraMouseClicked
        
        frameCompra();
        
    }//GEN-LAST:event_ButtonCompraMouseClicked

    private void ButtomVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtomVendaMouseClicked
        
        frameVenda();
        
    }//GEN-LAST:event_ButtomVendaMouseClicked

    private void ButtomRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtomRelatorioMouseClicked
        
        frameRelatorio();
        
    }//GEN-LAST:event_ButtomRelatorioMouseClicked

    private void menuItemCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemCompraMouseClicked
     
    }//GEN-LAST:event_menuItemCompraMouseClicked

    private void menuItemVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemVendaMouseClicked

    }//GEN-LAST:event_menuItemVendaMouseClicked

    private void menuItemRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemRelatorioMouseClicked

    }//GEN-LAST:event_menuItemRelatorioMouseClicked

    private void menuItemCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCompraActionPerformed
        
        frameCompra();
        
    }//GEN-LAST:event_menuItemCompraActionPerformed

    private void menuItemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioActionPerformed
        
        frameRelatorio();
        
    }//GEN-LAST:event_menuItemRelatorioActionPerformed

    private void sobreItemCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreItemCreditosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sobreItemCreditosMouseClicked

    private void sobreItemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreItemCreditosActionPerformed
        
        frameCreditos();
        
    }//GEN-LAST:event_sobreItemCreditosActionPerformed

    private void menuItemSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSairMouseClicked

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        
        opcaoSair();
        
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void ButtonCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCadastroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCadastroMouseClicked

    private void ButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastroActionPerformed
     
        frameCadastro();
        
    }//GEN-LAST:event_ButtonCadastroActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        frameCadastro();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void opcaoSair() {                                   

        int opcao = JOptionPane.showConfirmDialog(null,"Realmente deseja sair?","Central Control System", JOptionPane.YES_NO_CANCEL_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(0);
        } 
        else if (opcao == JOptionPane.NO_OPTION){
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }
    
    private void frameCompra(){
    
        FrameCompra frameCompra = new FrameCompra();
        frameCompra.setVisible(true);
        
    }
    
    private void frameVenda(){
    
        FrameVenda frameVenda = new FrameVenda();
        frameVenda.setVisible(true);
        
    }
    
    public void frameRelatorio(){
        
        FrameRelatorio frameRelatorio = new FrameRelatorio();
        frameRelatorio.setVisible(true);
    }
    
    private void frameCreditos(){
    
        FrameCreditos frameCreditos = new FrameCreditos();
        frameCreditos.setVisible(true);
        
    }
    
    private void frameCadastro() {
        
        FrameCadastro frameCadastro = new FrameCadastro();
        frameCadastro.setVisible(true);
                
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtomRelatorio;
    private javax.swing.JButton ButtomVenda;
    private javax.swing.JButton ButtonCadastro;
    private javax.swing.JButton ButtonCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemCompra;
    private javax.swing.JMenuItem menuItemRelatorio;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemVenda;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem sobreItemCreditos;
    // End of variables declaration//GEN-END:variables
}
