/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccsPackage;

/**
 *
 * @author Alyph
 */
public class FrameCreditos extends javax.swing.JDialog {

    /**
     * Creates new form FrameCreditos
     */
    public FrameCreditos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRelatorio = new javax.swing.JLabel();
        ButtonFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelRelatorio1 = new javax.swing.JLabel();
        labelRelatorio2 = new javax.swing.JLabel();
        labelRelatorio3 = new javax.swing.JLabel();
        labelRelatorio4 = new javax.swing.JLabel();
        labelRelatorio5 = new javax.swing.JLabel();
        labelRelatorio6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Central Control System - Créditos");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(565, 476));
        setMinimumSize(new java.awt.Dimension(565, 476));
        setResizable(false);
        setSize(new java.awt.Dimension(565, 476));

        labelRelatorio.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        labelRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRelatorio.setText("Créditos");

        ButtonFechar.setText("Fechar");
        ButtonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonFecharMouseClicked(evt);
            }
        });
        ButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFecharActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Version: CCS 1.0 (Build 1)\nActualizations: Coming Soon\nDevelopment: Netbeans IDE 8.1\nJava Version: Java(TM) SE Runtime Environment 1.8.0_101-b13\n\nSão Paulo / SP - Brasil \t\t\t    16/12/2016");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setMaximumSize(new java.awt.Dimension(480, 100));
        jTextArea1.setMinimumSize(new java.awt.Dimension(480, 100));
        jTextArea1.setPreferredSize(new java.awt.Dimension(480, 100));
        jScrollPane1.setViewportView(jTextArea1);

        labelRelatorio1.setFont(labelRelatorio1.getFont().deriveFont(labelRelatorio1.getFont().getStyle() | java.awt.Font.BOLD));
        labelRelatorio1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRelatorio1.setText("Aurélio Gualda (Aurelio.gualda@gmail.com)");
        labelRelatorio1.setMaximumSize(new java.awt.Dimension(113, 15));
        labelRelatorio1.setMinimumSize(new java.awt.Dimension(113, 15));
        labelRelatorio1.setPreferredSize(new java.awt.Dimension(113, 15));

        labelRelatorio2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        labelRelatorio2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRelatorio2.setText("Developers:");

        labelRelatorio3.setFont(labelRelatorio3.getFont().deriveFont(labelRelatorio3.getFont().getStyle() | java.awt.Font.BOLD));
        labelRelatorio3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRelatorio3.setText("Álypher Mansano (Alypher@gmail.com)");
        labelRelatorio3.setMaximumSize(new java.awt.Dimension(113, 15));
        labelRelatorio3.setMinimumSize(new java.awt.Dimension(113, 15));
        labelRelatorio3.setName(""); // NOI18N
        labelRelatorio3.setPreferredSize(new java.awt.Dimension(113, 15));

        labelRelatorio4.setFont(labelRelatorio4.getFont().deriveFont(labelRelatorio4.getFont().getStyle() | java.awt.Font.BOLD));
        labelRelatorio4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRelatorio4.setText("Tomas Herculano (TomasHerculano@gmail.com)");
        labelRelatorio4.setMaximumSize(new java.awt.Dimension(113, 15));
        labelRelatorio4.setMinimumSize(new java.awt.Dimension(113, 15));
        labelRelatorio4.setPreferredSize(new java.awt.Dimension(113, 15));

        labelRelatorio5.setFont(labelRelatorio5.getFont().deriveFont(labelRelatorio5.getFont().getStyle() | java.awt.Font.BOLD));
        labelRelatorio5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRelatorio5.setText("Gustavo Koltz (Gustavo.koltz@gmail.com)");
        labelRelatorio5.setMaximumSize(new java.awt.Dimension(113, 15));
        labelRelatorio5.setMinimumSize(new java.awt.Dimension(113, 15));
        labelRelatorio5.setPreferredSize(new java.awt.Dimension(113, 15));

        labelRelatorio6.setFont(labelRelatorio6.getFont().deriveFont(labelRelatorio6.getFont().getStyle() | java.awt.Font.BOLD));
        labelRelatorio6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRelatorio6.setText("Jefferson Pedro (JeffersonPedro89@hotmail.com)");
        labelRelatorio6.setMaximumSize(new java.awt.Dimension(113, 15));
        labelRelatorio6.setMinimumSize(new java.awt.Dimension(113, 15));
        labelRelatorio6.setPreferredSize(new java.awt.Dimension(113, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelRelatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelRelatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelRelatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelRelatorio5, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelRelatorio6, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelRelatorio4, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(ButtonFechar)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(labelRelatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(labelRelatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(labelRelatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(labelRelatorio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelRelatorio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(labelRelatorio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ButtonFechar)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonFecharMouseClicked

        this.dispose();        
    }//GEN-LAST:event_ButtonFecharMouseClicked

    private void ButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCreditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelRelatorio;
    private javax.swing.JLabel labelRelatorio1;
    private javax.swing.JLabel labelRelatorio2;
    private javax.swing.JLabel labelRelatorio3;
    private javax.swing.JLabel labelRelatorio4;
    private javax.swing.JLabel labelRelatorio5;
    private javax.swing.JLabel labelRelatorio6;
    // End of variables declaration//GEN-END:variables
}
